import os
import uuid
import json
import logging
import asyncio
import httpx
import subprocess
from fastapi import Request, HTTPException

logger = logging.getLogger("spark.backend.chained_generator")


async def generate_story(request: Request, ollama_url: str, comfyui_url: str, f5_tts_url: str, output_dir: str):
    try:
        body = await request.json()
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid JSON body")
    return await generate_story_from_params(body, ollama_url, comfyui_url, f5_tts_url, output_dir)


async def generate_story_from_params(body: dict, ollama_url: str, comfyui_url: str, f5_tts_url: str, output_dir: str):

    topic = body.get("prompt", "")
    scenes_count = int(body.get("scenes_count", 3))
    voice = body.get("voice", "en")
    style = body.get("style", "Cinematic")
    image_model = body.get("image_model", "flux1-schnell-q8.gguf")

    if not topic.strip():
        raise HTTPException(status_code=400, detail="Topic prompt is required")

    job_id = f"story_{uuid.uuid4().hex[:8]}"
    temp_dir = os.path.join(output_dir, f"temp_{job_id}")
    os.makedirs(temp_dir, exist_ok=True)

    # Step 1: Generate script outline using Ollama JSON mode
    logger.info(f"[{job_id}] Step 1: Generating script via Ollama...")
    system_prompt = (
        f"You are a creative visual storyboard director. Generate a storyboard script with exactly {scenes_count} scenes "
        f"based on the user's topic. You MUST output a JSON array of objects, where each object has exactly two fields: "
        f"1. 'narration': a single descriptive sentence describing the story narration for this scene.\n"
        f"2. 'image_prompt': a highly descriptive, visually rich prompt to generate the scene's image. "
        f"Integrate the style '{style}' into the image_prompt.\n"
        f"Do not write any introductory or concluding text. Return only the JSON list."
    )

    ollama_payload = {
        "model": "qwen3:8b" if "8b" in topic.lower() else "qwen3:14b", # Default to 14b, fallback to 8b
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Topic: {topic}"}
        ],
        "format": "json",
        "stream": False
    }

    # Fallback to whatever model is available in Ollama if our preferred model fails
    try:
        async with httpx.AsyncClient(timeout=60.0) as client:
            r = await client.get(f"{ollama_url}/api/tags")
            if r.status_code == 200:
                available_models = [m["name"] for m in r.json().get("models", [])]
                if available_models:
                    # Prefer qwen3:14b, then 8b, then whatever is first
                    if "qwen3:14b" in available_models:
                        ollama_payload["model"] = "qwen3:14b"
                    elif "qwen3:8b" in available_models:
                        ollama_payload["model"] = "qwen3:8b"
                    else:
                        ollama_payload["model"] = available_models[0]
    except Exception as e:
        logger.warning(f"Could not check Ollama models, using default: {e}")

    try:
        async with httpx.AsyncClient(timeout=120.0) as client:
            r = await client.post(f"{ollama_url}/api/chat", json=ollama_payload)
            if r.status_code != 200:
                raise HTTPException(status_code=502, detail=f"Ollama script gen failed: {r.text}")
            response_json = r.json()
            content = response_json.get("message", {}).get("content", "").strip()
            scenes = json.loads(content)
    except Exception as e:
        logger.error(f"Failed to generate story script JSON: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to generate storyboard script: {str(e)}")

    # Normalize JSON list format if LLM returned an object wrapper
    if isinstance(scenes, dict):
        for val in scenes.values():
            if isinstance(val, list):
                scenes = val
                break
        else:
            if "narration" in scenes or "image_prompt" in scenes:
                scenes = [scenes]

    if not isinstance(scenes, list) or len(scenes) == 0:
        raise HTTPException(status_code=500, detail="Invalid script format generated by LLM")

    # Limit to scenes_count
    scenes = scenes[:scenes_count]
    logger.info(f"[{job_id}] Script generated successfully with {len(scenes)} scenes.")

    generated_media = []

    # Step 2: Generate Audio & Images in parallel for all scenes
    for idx, scene in enumerate(scenes):
        scene_id = f"{job_id}_scene_{idx}"
        narration = scene.get("narration", "")
        img_prompt = scene.get("image_prompt", "")
        
        logger.info(f"[{job_id}] Processing Scene {idx}: Narration: '{narration}' | Image Prompt: '{img_prompt}'")
        
        # A. Synthesize TTS
        audio_file = os.path.join(temp_dir, f"audio_{idx}.wav")
        try:
            async with httpx.AsyncClient(timeout=120.0) as client:
                tts_payload = {"text": narration, "voice": voice, "speed": 1.0}
                r = await client.post(f"{f5_tts_url}/synthesize", json=tts_payload)
                if r.status_code == 200:
                    with open(audio_file, "wb") as f:
                        f.write(r.content)
                else:
                    raise Exception(f"F5-TTS returned {r.status_code}")
        except Exception as e:
            logger.error(f"Scene {idx} TTS generation failed: {e}")
            # Fallback to dummy silence if F5 fails
            cmd = ["ffmpeg", "-y", "-f", "lavfi", "-i", "anullsrc=r=44100:cl=mono", "-t", "5", audio_file]
            p = await asyncio.create_subprocess_exec(
                *cmd, stdout=asyncio.subprocess.DEVNULL, stderr=asyncio.subprocess.DEVNULL
            )
            try:
                await asyncio.wait_for(p.communicate(), timeout=180.0)
            except asyncio.TimeoutError:
                try:
                    p.kill()
                except Exception:
                    pass

        # B. Generate Image
        image_file = os.path.join(temp_dir, f"image_{idx}.png")
        try:
            # We construct a minimal ComfyUI workflow for Flux Schnell
            is_flux = "flux" in image_model.lower()
            is_zimage = "z_image" in image_model.lower()
            
            if is_zimage:
                workflow = {
                    "prompt": {
                        "10": {"class_type": "UNETLoader", "inputs": {"unet_name": image_model, "weight_dtype": "default"}},
                        "11": {"class_type": "CLIPLoaderGGUF", "inputs": {"clip_name": "Qwen3-4B-UD-Q8_K_XL.gguf", "type": "lumina2"}},
                        "12": {"class_type": "VAELoader", "inputs": {"vae_name": "ae.safetensors"}},
                        "13": {"class_type": "ModelSamplingAuraFlow", "inputs": {"model": ["10", 0], "shift": 3.0}},
                        "5": {"class_type": "EmptySD3LatentImage", "inputs": {"width": 1024, "height": 1024, "batch_size": 1}},
                        "6": {"class_type": "CLIPTextEncode", "inputs": {"text": img_prompt, "clip": ["11", 0]}},
                        "7": {"class_type": "CLIPTextEncode", "inputs": {"text": "blurry, low quality, distorted", "clip": ["11", 0]}},
                        "3": {
                            "class_type": "KSampler",
                            "inputs": {
                                "seed": 42 + idx, "steps": 8, "cfg": 1.0, "sampler_name": "euler_ancestral",
                                "scheduler": "normal", "denoise": 1.0, "model": ["13", 0],
                                "positive": ["6", 0], "negative": ["7", 0], "latent_image": ["5", 0]
                            }
                        },
                        "8": {"class_type": "VAEDecode", "inputs": {"samples": ["3", 0], "vae": ["12", 0]}},
                        "9": {"class_type": "SaveImage", "inputs": {"filename_prefix": scene_id, "images": ["8", 0]}}
                    }
                }
            else: # FLUX Schnell workflow (default)
                workflow = {
                    "prompt": {
                        "10": {"class_type": "UnetLoaderGGUF", "inputs": {"unet_name": image_model}},
                        "11": {"class_type": "DualCLIPLoader", "inputs": {"clip_name1": "t5xxl_fp8_e4m3fn.safetensors", "clip_name2": "clip_l.safetensors", "type": "flux"}},
                        "12": {"class_type": "VAELoader", "inputs": {"vae_name": "ae.safetensors"}},
                        "5": {"class_type": "EmptyLatentImage", "inputs": {"width": 1024, "height": 1024, "batch_size": 1}},
                        "6": {"class_type": "CLIPTextEncode", "inputs": {"text": img_prompt, "clip": ["11", 0]}},
                        "7": {"class_type": "CLIPTextEncode", "inputs": {"text": "blurry, low quality", "clip": ["11", 0]}},
                        "3": {
                            "class_type": "KSampler",
                            "inputs": {
                                "seed": 42 + idx, "steps": 4, "cfg": 1.0, "sampler_name": "euler",
                                "scheduler": "normal", "denoise": 1.0, "model": ["10", 0],
                                "positive": ["6", 0], "negative": ["7", 0], "latent_image": ["5", 0]
                            }
                        },
                        "8": {"class_type": "VAEDecode", "inputs": {"samples": ["3", 0], "vae": ["12", 0]}},
                        "9": {"class_type": "SaveImage", "inputs": {"filename_prefix": scene_id, "images": ["8", 0]}}
                    }
                }

            async with httpx.AsyncClient(timeout=120.0) as client:
                r = await client.post(f"{comfyui_url}/prompt", json=workflow)
                if r.status_code != 200:
                    raise Exception(f"ComfyUI prompt submit rejected: {r.text}")
                prompt_id = r.json().get("prompt_id")
                
                # Poll history
                completed = False
                for _ in range(60):
                    await asyncio.sleep(2)
                    hist = await client.get(f"{comfyui_url}/history/{prompt_id}")
                    if hist.status_code == 200:
                        history = hist.json()
                        if prompt_id in history:
                            completed = True
                            outputs = history[prompt_id].get("outputs", {})
                            for node_id, node_output in outputs.items():
                                if "images" in node_output and node_output["images"]:
                                    filename = node_output["images"][0].get("filename")
                                    comfy_output = os.path.join(
                                        os.getenv("COMFYUI_OUTPUT_DIR", "/comfyui-output"),
                                        filename,
                                    )
                                    if os.path.exists(comfy_output):
                                        import shutil
                                        shutil.copy(comfy_output, image_file)
                            break
                if not completed or not os.path.exists(image_file):
                    raise Exception("ComfyUI polling timed out or image missing")
        except Exception as e:
            logger.error(f"Scene {idx} image generation failed: {e}")
            # Fallback to dummy black image
            cmd = ["ffmpeg", "-y", "-f", "lavfi", "-i", "color=c=black:s=1024x1024", "-vframes", "1", image_file]
            p = await asyncio.create_subprocess_exec(
                *cmd, stdout=asyncio.subprocess.DEVNULL, stderr=asyncio.subprocess.DEVNULL
            )
            try:
                await asyncio.wait_for(p.communicate(), timeout=180.0)
            except asyncio.TimeoutError:
                try:
                    p.kill()
                except Exception:
                    pass

        generated_media.append((image_file, audio_file))

    # Step 3: Compile final video via FFmpeg
    logger.info(f"[{job_id}] Step 3: Compiling story scenes into video...")
    scene_videos = []
    
    for idx, (img_p, aud_p) in enumerate(generated_media):
        scene_mp4 = os.path.join(temp_dir, f"scene_{idx}.mp4")
        # Generate scene video matching the audio length
        cmd = [
            "ffmpeg", "-y",
            "-loop", "1", "-framerate", "25", "-i", img_p,
            "-i", aud_p,
            "-c:v", "libx264", "-tune", "stillimage",
            "-c:a", "aac", "-b:a", "192k", "-ar", "44100", "-ac", "2",
            "-pix_fmt", "yuv420p", "-vf", "scale=1024:1024",
            "-shortest", scene_mp4
        ]
        p = await asyncio.create_subprocess_exec(
            *cmd, stdout=asyncio.subprocess.DEVNULL, stderr=asyncio.subprocess.DEVNULL
        )
        try:
            await asyncio.wait_for(p.communicate(), timeout=180.0)
        except asyncio.TimeoutError:
            try:
                p.kill()
            except Exception:
                pass
        if os.path.exists(scene_mp4):
            scene_videos.append(scene_mp4)

    if not scene_videos:
        raise HTTPException(status_code=500, detail="FFmpeg compilation failed to produce any scene videos.")

    # Concat all scene videos
    concat_txt = os.path.join(temp_dir, "concat.txt")
    with open(concat_txt, "w") as f:
        for v in scene_videos:
            f.write(f"file '{v}'\n")

    output_filename = f"{job_id}.mp4"
    output_filepath = os.path.join(output_dir, output_filename)
    
    cmd_concat = [
        "ffmpeg", "-y",
        "-f", "concat", "-safe", "0",
        "-i", concat_txt,
        "-c", "copy",
        output_filepath
    ]
    p = await asyncio.create_subprocess_exec(
        *cmd_concat, stdout=asyncio.subprocess.DEVNULL, stderr=asyncio.subprocess.DEVNULL
    )
    try:
        await asyncio.wait_for(p.communicate(), timeout=180.0)
    except asyncio.TimeoutError:
        try:
            p.kill()
        except Exception:
            pass

    # Cleanup temp directory
    try:
        import shutil
        shutil.rmtree(temp_dir)
    except Exception as e:
        logger.warning(f"Could not clean up temp dir {temp_dir}: {e}")

    if os.path.exists(output_filepath) and os.path.getsize(output_filepath) > 0:
        return {
            "job_id": job_id,
            "status": "completed",
            "output_url": f"/output/{output_filename}",
            "script": scenes
        }
    else:
        raise HTTPException(status_code=500, detail="FFmpeg video compilation failed")
